name: car_ads_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  smooth_page_indicator: ^1.2.0+3
  skeletonizer: ^1.4.2
  flutter_spinkit: ^5.2.1
  cloud_firestore: ^5.4.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/


  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/Avenir Black.ttf
          weight: 700
        - asset: assets/fonts/Avenir Regular.ttf
          weight: 400