// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjaacOPzH9R0PtwO0qhwHM0gA5xg7e4k',
    appId: '1:978419796746:web:1eaa08a37d4ac0c605c8f3',
    messagingSenderId: '978419796746',
    projectId: 'carads-app',
    authDomain: 'carads-app.firebaseapp.com',
    storageBucket: 'carads-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Ny31mwiQWWmjKxrkVoo3kmsD3QbORo4',
    appId: '1:978419796746:android:f1681fca6a25955a05c8f3',
    messagingSenderId: '978419796746',
    projectId: 'carads-app',
    storageBucket: 'carads-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnenSupPSB5kvY7d5bgVOF6-6HsjfQvzE',
    appId: '1:978419796746:ios:9862cfb3325382aa05c8f3',
    messagingSenderId: '978419796746',
    projectId: 'carads-app',
    storageBucket: 'carads-app.appspot.com',
    iosBundleId: 'com.example.carAdsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnenSupPSB5kvY7d5bgVOF6-6HsjfQvzE',
    appId: '1:978419796746:ios:9862cfb3325382aa05c8f3',
    messagingSenderId: '978419796746',
    projectId: 'carads-app',
    storageBucket: 'carads-app.appspot.com',
    iosBundleId: 'com.example.carAdsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjaacOPzH9R0PtwO0qhwHM0gA5xg7e4k',
    appId: '1:978419796746:web:a5cd159f54c9b11d05c8f3',
    messagingSenderId: '978419796746',
    projectId: 'carads-app',
    authDomain: 'carads-app.firebaseapp.com',
    storageBucket: 'carads-app.appspot.com',
  );
}
